version: '3.3'

services:
  image-placeholder-server:
    image: golang:1.10
    ports:
      - 8080:8080
    command: go run /go/src/app/main.go server start
    volumes:
      - ./:/go/src/app

volumes:
  mongodb-data: {}
